name: Test Unbound with Multiple Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-unbound:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        unbound-version: [1.17.0, 1.18.0, 1.19.3, 1.21.1, 1.22.0]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Start Unbound containers
        run: UNBOUND_VERSION=${{ matrix.unbound-version }} docker-compose up -d
      - name: Verify Unbound is running
        run: docker ps
      - name: Test Unbound
        run: dig @unbound-${{ matrix.unbound-version }} example.com
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - run: npm run test:it
      - name: Stop Unbound
        run: |
          docker compose stop unbound-${{ matrix.unbound-version }}
